In [1]:
import pandas as pd

In [2]:
# read data from csv file\
df = pd.read_csv('../../data-analytics/datasets/meals/FinalMeals.csv')

In [3]:
df.head()

,Main Meal,Side Meal,Breakfast_Probability,Lunch_Probability,Dinner_Probability,Combined_Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,...,Phosphorus(mg),Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Price
0,Kottu Roti,Chicken Curry,1.0,2.5,8.0,1,Kottu Roti with Chicken Curry,"Roti, carrot, leeks, Chicken, Coconut Oil, Ch...","30, 20, 27.5, 70.0, 5, 2.5, 20.0, 5.0, 3.0","SLI019, SLB002, SLD055, SLH006, SLK004, SLK002...",...,242.7032,68.4165,41.98655,584.061,9412.309,2063.6709,835.6485,2.31535,24.0562,168.900
1,Kottu Roti,Devilled Chicken,1.0,2.5,8.0,1,Kottu Roti with Devilled Chicken,"Roti, carrot, leeks, Chicken, Coconut Oil, Ch...","30, 20, 27.5, 70.0, 5, 7.5, 10.0, 20.0","SLI019, SLB002, SLD055, SLH006, SLK004, SLK002...",...,202.0175,63.7480,41.89725,518.101,801.731,804.1420,616.0965,1.09825,24.3140,178.930
2,Kottu Roti,Devilled Fish,1.0,2.5,8.0,1,Kottu Roti with Devilled Fish,"Roti, carrot, leeks, Chicken, Coconut Oil, Ch...","30, 20, 27.5, 20, 5, 7.5, 50.0, 5.0, 20.0","SLI019, SLB002, SLD055, SLH006, SLK004, SLK002...",...,261.2955,62.8230,43.12925,573.501,1514.681,848.9505,1103.7465,1.06725,24.1670,348.930
3,Kottu Roti,Seer Fish Curry,1.0,2.5,8.0,1,Kottu Roti with Seer Fish Curry,"Roti, carrot, leeks, Chicken, Coconut Oil, Ch...","30, 20, 27.5, 20, 5, 12.5, 50.0, 25.0","SLI019, SLB002, SLD055, SLH006, SLK004, SLK002...",...,304.5530,60.5835,43.05575,650.951,12247.829,1762.4700,1318.2885,2.59775,23.8960,341.900
4,Kiribath,Seeni Sambol,9.0,1.0,0.0,1,Kiribath with Seeni Sambol,"Rice, Coconut milk, Onion, Sugar, chillii","85, 15, 50.0, 5.0, 5.0","SLA009, SLI005, SLD060, SLI011, SLK002",...,215.7965,78.3285,12.79200,440.200,6976.655,1049.0970,779.0950,6.40750,64.8125,41.975

In [4]:
# in this gets only  Complete Meal , Ingredients , Quantities columns and  prepare new dataset
df_new = df[['Complete Meal', 'Ingredients', 'Quantities']]

In [5]:
# write new dataset to csv file
df_new.to_csv('../../data-analytics/datasets/meals/FinalMealsForChatbot.csv', index=False)